//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("Provides an easy way to place a list of links on a website")]
[assembly: System.Reflection.AssemblyCompany("DotNetNuke")]
[assembly: System.Reflection.AssemblyProduct("Links")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2021")]
[assembly: System.Reflection.AssemblyVersion("8.0.2.00")]
[assembly: System.Reflection.AssemblyTitle("DotNetNuke Links Module")]


